### ISSUE TITLE
Windows binaries and chess engine by Henning Sperr

### ISSUE THREAD

**Issue by yellow-panther** [maksimKorzh/chengine#1]
Windows exe-files cf. https://github.com/maksimKorzh/Chenglite/issues/1

Does your programm have anything in common with https://github.com/hsperr/Chengine - https://drive.google.com/file/d/0B-PM8aD2-9I4ZF9McXlHVzRlb3c/view ?

**Comment by maksimKorzh** [comment]
windows executables for Chenglite are now available
